'use strict';mix_d("SimilaritiesUICards__p13n-desktop-sims-fbt:p13n-desktop-sims-fbt__w446Be5k",["exports","tslib","@c/browser-operations","@c/scoped-dom","@c/error-handling"],function(N,E,T,U,V){function H(b){return b&&"object"===typeof b&&"default"in b?b:{"default":b}}var W=H(T),d=H(U),I=H(V),X=function(b,e){e?b.classList.add("add-to-cart-item-disabled"):b.classList.remove("add-to-cart-item-disabled");b.querySelectorAll("input").forEach(function(n){e?n.setAttribute("disabled","true"):n.removeAttribute("disabled")})},
O=function(b,e){b=d["default"].cardRoot.querySelector("#add-to-cart-item-"+b);if(!b)return I["default"].error('Missing Add to Cart item!", "add-to-cart.client.item-state-handler',"changeItemStatus");if(!(e&&b.classList.contains("add-to-cart-item-disabled")||!e&&!b.classList.contains("add-to-cart-item-disabled"))){X(b,e);var n;for(b=e=0;3>b;b++){var a=d["default"].cardRoot.querySelector("#add-to-cart-item-"+b);if(!a)break;a.classList.contains("add-to-cart-item-disabled")||e++}var c=d["default"].cardRoot.getElementsByClassName("add-to-cart-section")[0];
b=c.getElementsByClassName("a-button-text")[0];a=c.getElementsByClassName("add-to-cart-button")[0];c=c.getElementsByClassName("add-to-cart-string-data")[0];if(null===(n=null===c||void 0===c?void 0:c.dataset)||void 0===n?0:n.displayStringList)var h=JSON.parse(c.dataset.displayStringList);a&&(0===e?a.classList.add("a-button-disabled"):a.classList.remove("a-button-disabled"));b?h&&h.length>e?b.innerText=h[e]:I["default"].error('Missing Add to Cart string!", "add-to-cart.client.item-state-handler',"updateButtonString"):
I["default"].error('Missing Add to Cart button!", "add-to-cart.client.item-state-handler',"updateButtonString")}},S=function(b){return E.__awaiter(void 0,void 0,void 0,function(){var e,n,a,c,h,f,w,J,x,y,p,K,q,r,z,L,A,P,t,u;return E.__generator(this,function(v){if((a=d["default"].cardRoot.getElementsByClassName("cardRoot")[0])&&"true"===a.dataset.punt)return[2];c=1;a&&a.dataset.count&&(c=Number(a.dataset.count));a&&a.dataset.components&&(h=JSON.parse(a.dataset.components));a&&a.dataset.addToCart&&
(f=JSON.parse(a.dataset.addToCart));a&&a.dataset.priceTotals&&(w=JSON.parse(a.dataset.priceTotals));a&&a.dataset.pointsTotal&&(J=JSON.parse(a.dataset.pointsTotal));if(h&&w){v=h;for(var B=c,C=[],k=[],g=0;g<B;g++){var l=g+1;1<l&&(C[g]=d["default"].cardRoot.getElementsByClassName("thumbnailPlus-"+String(l))[0]);k[g]=d["default"].cardRoot.getElementsByClassName("thumbnail-"+String(l))[0]}var M=!1,Q=0,R="";for(g=0;g<B;g++){l=String(g+1);var D=C[g],F=k[g];v[l]&&v[l].checked?(O(g,!1),Q++,R+=l,0===g?M=!0:
D&&(M?D.style.display="unset":(M=!0,D.style.display="none")),F&&(F.style.display="unset")):(O(g,!0),D&&(D.style.display="none"),F&&(F.style.display="none"))}e=Q;n=R;v=h;B=c;C=[];for(k=0;k<B;k++)g=k+1,C[k]=d["default"].cardRoot.getElementsByClassName("asin-"+String(g))[0];for(k=0;k<B;k++)g=String(k+1),l=C[k],v[g]&&v[g].checked?l&&(l.style.opacity="100%"):l&&(l.style.opacity="50%");x=e;y=w[n];p=d["default"].cardRoot.getElementsByClassName(b.totalLabel)[0];K=d["default"].cardRoot.getElementsByClassName(b.totalAmount)[0];
q=d["default"].cardRoot.getElementsByClassName(b.addItems)[0];r=d["default"].cardRoot.getElementsByClassName(b.chooseItems)[0];z=d["default"].cardRoot.getElementsByClassName(b.actionDetails)[0];0===x?(q&&(q.style.display="none"),p&&(p.style.display="none"),r&&(r.style.display="unset"),z&&(z.style.visibility="hidden")):(y?(p&&K&&(K.innerText=y,p.style.display="block"),q&&(q.style.display="none"),r&&(r.style.display="none")):(q&&(q.style.display="inline-block"),r&&(r.style.display="none"),p&&(p.style.display=
"none")),z&&(z.style.visibility="visible"));a&&h&&J&&(L=d["default"].cardRoot.getElementsByClassName(b.pointsAmount)[0],A=d["default"].cardRoot.getElementsByClassName(b.totalPointsLabel)[0],(P=J[n])?A&&L&&(L.innerText=P,A.style.display="block"):A&&(A.style.display="none"));if(t=d["default"].cardRoot.getElementsByClassName(b.buttonSection)[0])u=t.getElementsByClassName("a-button-text")[0],0===x?t.classList.contains("a-button-disabled")||t.classList.add("a-button-disabled"):(t.classList.contains("a-button-disabled")&&
t.classList.remove("a-button-disabled"),u&&t.classList.contains("add-to-cart-button")?u.innerText+=": "+y:u&&f&&f.length>=x&&(u.innerText=f[x-1]+": "+y))}return[2]})})},G;(function(b){b.clickHandler="clickHandler";b.checkHandler="checkHandler";b.popupHandler="popupHandler"})(G||(G={}));var m={simsFbtContainter:"_p13n-desktop-sims-fbt_fbt-desktop_sims-fbt-containter__2Cffh",thumbnailBox:"_p13n-desktop-sims-fbt_fbt-desktop_thumbnail-box__4jnIT",thumbnailPlus:"_p13n-desktop-sims-fbt_fbt-desktop_thumbnail-plus__zdWox",
productBox:"_p13n-desktop-sims-fbt_fbt-desktop_product-box__3PBxY",itemDetailsPerAsin:"_p13n-desktop-sims-fbt_fbt-desktop_item-details-per-asin__3DtF1",itemDeliveryMessagePerAsin:"_p13n-desktop-sims-fbt_fbt-desktop_item-delivery-message-per-asin__WQ7q7",fbtItemCheck:"_p13n-desktop-sims-fbt_fbt-desktop_fbt-item-check__pUIoy",addAllButton:"_p13n-desktop-sims-fbt_fbt-desktop_add-all-button__1TRXG",totalLabel:"_p13n-desktop-sims-fbt_fbt-desktop_total-label__dI983",totalPointsLabel:"_p13n-desktop-sims-fbt_fbt-desktop_total-points-label__3r09H",
addItems:"_p13n-desktop-sims-fbt_fbt-desktop_add-items__16weX",chooseItems:"_p13n-desktop-sims-fbt_fbt-desktop_choose-items__15UQx",totalAmount:"_p13n-desktop-sims-fbt_fbt-desktop_total-amount__wLVdU",pointsAmount:"_p13n-desktop-sims-fbt_fbt-desktop_points-amount__1SNdT",priceAddToCartBox:"_p13n-desktop-sims-fbt_fbt-desktop_price-add-to-cart-box__3OUdK",shipMessageBox:"_p13n-desktop-sims-fbt_fbt-desktop_ship-message-box__t-OOr",shippingInfoShowBox:"_p13n-desktop-sims-fbt_fbt-desktop_shipping-info-show-box__17yWM",
shippingInfoShowWeblabC:"_p13n-desktop-sims-fbt_fbt-desktop_shipping-info-show-weblab-c__31wXV",shippingInfoShowWeblabT:"_p13n-desktop-sims-fbt_fbt-desktop_shipping-info-show-weblab-t__3U6Pz",showDetailsBox:"_p13n-desktop-sims-fbt_fbt-desktop_show-details-box__-R3Xb",showDetails:"_p13n-desktop-sims-fbt_fbt-desktop_show-details__3GnPL",hideDetails:"_p13n-desktop-sims-fbt_fbt-desktop_hide-details__28l17",simsFbtUnselectedItem:"_p13n-desktop-sims-fbt_fbt-desktop_sims-fbt-unselected-item__VQmZx",simsFbtRows:"_p13n-desktop-sims-fbt_fbt-desktop_sims-fbt-rows__2LJXs",
bucketDivider:"_p13n-desktop-sims-fbt_fbt-desktop_bucket-divider__25poP",titleTruncate:"_p13n-desktop-sims-fbt_fbt-desktop_title-truncate__1pPAM",detailRowElement:"_p13n-desktop-sims-fbt_fbt-desktop_detail-row-element__2WDgq",detailRowElementLeftMargin:"_p13n-desktop-sims-fbt_fbt-desktop_detail-row-element-left-margin__UkZ8O",actionDetails:"_p13n-desktop-sims-fbt_fbt-desktop_action-details__18ZiI"};N._operationNames=[];N.card=function(){return E.__awaiter(void 0,void 0,void 0,function(){var b,e;return E.__generator(this,
function(n){b=W["default"].setup().define;if(!d["default"].cardRoot)return[2];S(m);e=!0;b(G.clickHandler,"click",function(a){if(a.event.target){a=d["default"].cardRoot.getElementsByClassName(m.shippingInfoShowBox);var c=d["default"].cardRoot.getElementsByClassName(m.showDetails)[0],h=d["default"].cardRoot.getElementsByClassName(m.hideDetails)[0];c&&(e?(c.style.display="none",h.style.display="unset",a&&([].forEach.call(a,function(f,w){f.style.display="block"}),e=!1)):(c.style.display="unset",h.style.display=
"none",a&&[].forEach.call(a,function(f,w){f.style.display="none"}),e=!0))}});b(G.checkHandler,"click",function(a){a=a.event.target;if(!a||"fbtCheck"===a.id.substr(0,8)){for(;a&&!a.classList.contains(m.fbtItemCheck);)a=a.parentElement;if(a){var c=a.id,h=d["default"].cardRoot.getElementsByClassName("cardRoot")[0],f=void 0;h&&h.dataset.components&&(f=JSON.parse(h.dataset.components));f&&f[c]&&(f[c].checked=!f[c].checked);f&&f[c].checked&&(a.classList.contains(m.simsFbtUnselectedItem)&&a.classList.remove(m.simsFbtUnselectedItem),
a.classList.contains(m.fbtCheckDetails)||a.classList.add(m.fbtCheckDetails));f&&!f[c].checked&&(a.classList.remove(m.fbtCheckDetails),a.classList.add(m.simsFbtUnselectedItem));h.dataset.components=JSON.stringify(f);S(m)}}});return[2]})})}});
